package  org.flowerplatform.web.svn {
	import org.flowerplatform.common.plugin.AbstractFlowerFlexPlugin;
	import org.flowerplatform.web.svn.common.SvnCommonPlugin;
	/**
	 * @flowerModelElementId _FijBEAMwEeOrJqcAep-lCg
	 */
	public class SvnPlugin extends AbstractFlowerFlexPlugin  {
		/**
		 * @flowerModelElementId _syXvMAMzEeOrJqcAep-lCg
		 */
		public var svnCommonPlugin:SvnCommonPlugin;
		/**
		 * @flowerModelElementId _YDrY8AM7EeOrJqcAep-lCg
		 */
		private var INSTANCE:SvnPlugin;
		/**
		 * @flowerModelElementId _DxJioAM1EeOrJqcAep-lCg
		 */
		public override function preStart():void {	
			// TODO Auto-generated by Flower Dev Center
//			super.preStart();
		}
		/**
		 * @flowerModelElementId _DxQ3YAM1EeOrJqcAep-lCg
		 */
		protected override function registerClassAliases():void {	
			// TODO Auto-generated by Flower Dev Center
			super.registerClassAliases();
		}
		/**
		 * @flowerModelElementId _DxUhxAM1EeOrJqcAep-lCg
		 */
		public override function start():void {	
			// TODO Auto-generated by Flower Dev Center
			super.start();
		}
		/**
		 * @flowerModelElementId _tv-tUAM7EeOrJqcAep-lCg
		 */
		public function getInstance() {
			// TODO implement
		}
	}
}