<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="regex"
    nsURI="http://www.flower-platform.com/xmi/regex_1.0.0" nsPrefix="regex">
  <eClassifiers xsi:type="ecore:EClass" name="ParserRegex" eSuperTypes="#//MacroRegex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MacroRegex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parserRegexes" upperBound="-1"
        eType="#//ParserRegex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macroRegexes" upperBound="-1"
        eType="#//MacroRegex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extensions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
