package  org.flowerplatform.web.svn.common.action {
	import org.flowerplatform.flexutil.popup.ActionBase;
	/**
	 * @flowerModelElementId _DhlmAAMcEeOrJqcAep-lCg
	 */
	public class CreateRemoteFolderAction extends ActionBase  {
		/**
		 * @flowerModelElementId _-0ZzQAMdEeOrJqcAep-lCg
		 */
		public function CreateRemoteFolderAction() {
			// TODO implement
		}
		/**
		 * @flowerModelElementId _GWBDMAMhEeOrJqcAep-lCg
		 */
		public override function get visible():Boolean {	
			// TODO Auto-generated by Flower Dev Center
			return true;
		}
		/**
		 * @flowerModelElementId _TnF_EAMeEeOrJqcAep-lCg
		 */
		public override function run():void {
			// TODO implement
		}
	}
}