package  org.flowerplatform.web.svn.common {
	import org.flowerplatform.common.plugin.AbstractFlowerFlexPlugin;
	/**
	 * @flowerModelElementId _5Z5NMAMvEeOrJqcAep-lCg
	 */
	public class SvnCommonPlugin extends AbstractFlowerFlexPlugin  {
		/**
		 * @flowerModelElementId _fUOOYAM7EeOrJqcAep-lCg
		 */
		private var INSTANCE:SvnCommonPlugin;
		/**
		 * @flowerModelElementId _RqGPcAM1EeOrJqcAep-lCg
		 */
		public override function preStart():void {	
			// TODO Auto-generated by Flower Dev Center
			super.preStart();
		}
		/**
		 * @flowerModelElementId _RqKg4AM1EeOrJqcAep-lCg
		 */
		protected override function registerClassAliases():void {	
			// TODO Auto-generated by Flower Dev Center
			super.registerClassAliases();
		}
		/**
		 * @flowerModelElementId _RqOLQAM1EeOrJqcAep-lCg
		 */
		public override function start():void {	
			// TODO Auto-generated by Flower Dev Center
			super.start();
		}
		/**
		 * @flowerModelElementId _v7-q0AM7EeOrJqcAep-lCg
		 */
		public function getInstance() {
			// TODO implement
		}
	}
}