package org.flowerplatform.web.svn.explorer;


import org.flowerplatform.communication.tree.remote.TreeNode;
import org.flowerplatform.communication.tree.GenericTreeContext;
import org.flowerplatform.communication.tree.IChildrenProvider;

/**
 * Am vrea sa-l folosim ca provider atat pt. SvnRepository cat si pentru SvnFile.
 * 
 * @flowerModelElementId _STrA0P5nEeKrJqcAep-lCg
 */
public class SvnFile_ChildrenProvider implements IChildrenProvider {
	/**
	 * De vazut:
	 * 1) ce metoda tr apelata? e din javahl, sau subclipse?
	 * 2) ce tipuri de date returneaza? O lista de string? O lista de altceva?
	 * 
	 * @flowerModelElementId _iXg5EP6BEeKrJqcAep-lCg
	 */
	public Collection<Pair<Object, String>> getChildrenForNode(Object node,
			TreeNode treeNode, GenericTreeContext context) {
		// TODO Auto-generated by Flower Dev Center
		return super.getChildrenForNode(node, treeNode, context);
	}

	/**
	 * @flowerModelElementId _iXyl4P6BEeKrJqcAep-lCg
	 */
	public Boolean nodeHasChildren(Object node, TreeNode treeNode,
			GenericTreeContext context) {
		// TODO Auto-generated by Flower Dev Center
		return super.nodeHasChildren(node, treeNode, context);
	}
}