package org.flowerplatform.web.svn.explorer;


import org.flowerplatform.web.explorer.AbstractVirtualItemChildrenProvider;
import org.flowerplatform.communication.temp.tree.remote.GenericTreeStatefulService;
import org.flowerplatform.communication.tree.remote.GenericTreeStatefulService;
import org.flowerplatform.communication.tree.remote.TreeNode;
import org.flowerplatform.communication.tree.GenericTreeContext;
import org.flowerplatform.communication.tree.IGenericTreeStatefulServiceAware;

/**
 * @flowerModelElementId _UEfo0P2kEeKrJqcAep-lCg
 */
public class SvnRepositories_OrganizationChildrenProvider extends
		AbstractVirtualItemChildrenProvider implements
		IGenericTreeStatefulServiceAware {
	/**
	 * @flowerModelElementId _DjxSYP2tEeKrJqcAep-lCg
	 */
	public SvnRepositories_OrganizationChildrenProvider SvnRepositories_OrganizationChildrenProvider() {
		// TODO implement
		return null;
	}

	/**
	 * @flowerModelElementId _Upao4P2mEeKrJqcAep-lCg
	 */
	public GenericTreeStatefulService setGenericTreeStatefulService(
			GenericTreeStatefulService genericTreeStatefulService) {
		// TODO implement
		return null;
	}

	/**
	 * In faza 2, cand folosim BD, tr sa ne uitam acolo sa vedem daca avem date. 
	 * 
	 * @flowerModelElementId _RAmGAP6AEeKrJqcAep-lCg
	 */
	public Object getChildrenForNode(Object node, TreeNode treeNode,
			GenericTreeContext context) {
		// TODO Auto-generated by Flower Dev Center
		return super.getChildrenForNode(node, treeNode, context);
	}

	/**
	 * @flowerModelElementId _RA3y0P6AEeKrJqcAep-lCg
	 */
	public Boolean nodeHasChildren(Object node, TreeNode treeNode,
			GenericTreeContext context) {
		// TODO Auto-generated by Flower Dev Center
		return super.nodeHasChildren(node, treeNode, context);
	}
}