package org.flowerplatform.web.svn.explorer;

import java.util.Collection;
import java.util.Collections;

import org.flowerplatform.common.util.Pair;
import org.flowerplatform.communication.tree.GenericTreeContext;
import org.flowerplatform.communication.tree.IGenericTreeStatefulServiceAware;
import org.flowerplatform.communication.tree.remote.GenericTreeStatefulService;
import org.flowerplatform.communication.tree.remote.TreeNode;
import org.flowerplatform.web.explorer.AbstractVirtualItemChildrenProvider;
import org.flowerplatform.web.svn.SvnNodeType;

/**
 * Parent node = Organization (i.e. File).<br/>
 * Child node is a virtual item, i.e. Pair<Org File, nodeType>.
 * 
 * @author Victor Badila
 * 
 * @flowerModelElementId _UEfo0P2kEeKrJqcAep-lCg
 */

public class SvnRepositories_OrganizationChildrenProvider extends AbstractVirtualItemChildrenProvider implements IGenericTreeStatefulServiceAware {
	/**
	 * @flowerModelElementId _DjxSYP2tEeKrJqcAep-lCg
	 */
	public SvnRepositories_OrganizationChildrenProvider() {
		super();
		// TODO implement
		
		childNodeTypes = Collections.singletonList(SvnNodeType.NODE_TYPE_SVN_REPOSITORIES);		
	}

	/**
	 * @flowerModelElementId _Upao4P2mEeKrJqcAep-lCg
	 */
	
	@Override
	public void setGenericTreeStatefulService(GenericTreeStatefulService genericTreeStatefulService) {
		//SvnPlugin.getInstance().getTreeStatefulServicesDisplayingGitContent().add(genericTreeStatefulService);
	}

		
	/**
	 * In faza 2, cand folosim BD, tr sa ne uitam acolo sa vedem daca avem date. 
	 * 
	 * @flowerModelElementId _RAmGAP6AEeKrJqcAep-lCg
	 */
	public Collection<Pair<Object, String>> getChildrenForNode(Object node, TreeNode treeNode,
			GenericTreeContext context) {
		// TODO Auto-generated by Flower Dev Center
		return super.getChildrenForNode(node, treeNode, context);
	}

	/**
	 * @flowerModelElementId _RA3y0P6AEeKrJqcAep-lCg
	 */
	public Boolean nodeHasChildren(Object node, TreeNode treeNode,
			GenericTreeContext context) {
		// TODO Auto-generated by Flower Dev Center
		return super.nodeHasChildren(node, treeNode, context);
	}
}